### ISSUE TITLE
`jekyll serve` regeneration loops on error

### ISSUE THREAD

**Issue by paolobrasolin** [paolobrasolin/jekyll-antex#1]
When an `Antex::Command` throws an error (e.g. caused by invalid `TeX` code), if we're using incremental builds with the `jekyll serve`r, a rebuilding loop is entered.

**Comment by paolobrasolin** [comment]
`Antex` caching causes the loop, because `Jekyll` is listening to the cache folder too.
A solution is adding an exclusion to `_config.yml`:
```
exclude:
 - .antex-cache/'
```
A better solution would be to exclude the folder automatically with values from
```
antex:
  dirs:
    work: .antex-cache
    dest: .antex-cache/antex
```

**Comment by paolobrasolin** [comment]
Another solution could be to simply put the cache folder outside of the project root. E.g.:
```
antex:
  dirs:
    work: /home/username/.antex-cache
    dest: /home/username/.antex-cache/antex
```

Note the tilde `~` cannot be expanded, so you must use the full home path if you need it.
