### ISSUE TITLE
Make aliases/guards skippable

### ISSUE THREAD

**Issue by paolobrasolin** [paolobrasolin/jekyll-antex#14]
It should be possible to turn off default aliased and guards like this from Jekyll's `_config.yml`:

```
antex:
  guards:
    comment: false
  aliases:
    inline_math: false
```
